const images = {
  africa: require('./africa.png'),
  antarctica: require('./Antarctica.png'),
  asia: require('./asia.png'),
  northAmerica: require('./northAmerica.png'),
  southAmerica: require('./southAmerica.png'),
  glob: require('./globe.png'),
  message: require('./messenger.png'),
  profile: require('./user.png'),
  settings: require('./setting.png'),
  lock: require('./lock.png'),
  notification: require('./notification.png'),
  rightArrow: require('./rightArrow.png'),
  search: require('./search.png'),
  sendIcon: require('./sendIcon.png'),
  help: require('./help.png'),
  document: require('./document.png'),
  arrowBack: require('./arrowBack.png'),
  logout: require('./logout.png'),
  appLogo: require('./appLogo.png'),
  character: require('./character.png'),
  facebook: require('./facebook-logo.png'),
  google: require('./google-logo.png'),
  email: require('./email.png'),
  eye: require('./eye.png'),
  eyeEnable: require('./eyeEnable.png'),
};

export default images;
