export const Routes = {
  // AUTH STACK //

  WELCOME: 'welcome',
  LOGIN: 'login',
  SIGN_UP: 'signup',
  PRE_ONBOARDING: 'preOnboarding',
  ONBOARDING: 'OnBoarding',
  BOTTOM_TABS: 'bottomTabs',
  HOME_SCREEN: 'homeScreen',
  MESSAGE: 'message',
  PROFILE: 'profile',
  SETTINGS: 'settings',
  SPLASH: 'splash',
  NOTIFICATION_SETTINGS: 'notificationSettings',
  NEW_PASSWORD: 'newPassword',
  UPDATE_PASSWORD: 'updatePassword',
  PRIVACY_POLICY: 'privacyPolicy',
  START_SCREEN: 'startScreen',
  SEARCH: 'search',
  EDIT_PROFILE: 'editProfile',
  APPLICATIONS: 'applications',
  JOB_APPLY_SCREEN: 'jobApplyScreen',
  DRAWER: 'drawer',
  LOGOUT: 'logout',
};
